### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by AdamJSoftware** [arindas/laminarmq#10]
Seems that this project has had 0 activity for 4 months, which is sad as this seems to be really cool and decently close to being finished. Are you planning on working on this further, or is the project dead?

**Comment by arindas** [comment]
I am still working on other development branches. I have recently worked on a massive rewrite of the underlying segmented log data structure. Apart from this, I'm trying to make it easier to support multiple async runtimes.

Currently, I'm developing at the branch [`feature/glommio-storage`](https://github.com/arindas/laminarmq/tree/feature/glommio-storage)

Will merge that to [`dev/1`](https://github.com/arindas/laminarmq/tree/dev/1)

When we are ready with server components we will eventually merge back to `develop` and then `main`.

**Comment by arindas** [comment]
However, we still have a lot of work left. We need to verify and implement the designs for membership and replication.

Closing this issue for now.
