### ISSUE TITLE
API to integrate nodes into application

### ISSUE THREAD

**Issue by DXist** [arindas/laminarmq#9]
Hi,

Is it planned to expose API to embed mq server node into stateful application shard? And use local transports like channels to serve jobs for local partitions?

**Comment by arindas** [comment]
Yes, this is possible with the design we have planned. In our planned design, our workers listen on a channel for requests. When used as a server, a REST API server enqueues requests on the sending end of the channel.

However, in this case, there has to be a library to route messages to the appropriate threads servicing their partitions. Also one would need some other web APIs for replication. I'm unsure how the design would accommodate membership and replication in this case.

However, you can definitely have a single node single thread persistent queue that is locally available to your application.

**Comment by arindas** [comment]
Closing this issue for now.
